INSERT INTO tx_a11ycompanion_blacklistword (pid, word, hidden, deleted)
VALUES (0, 'Mehr lesen', 0, 0),
    (0, 'Read more', 0, 0),
    (0, 'more', 0, 0),
    (0, 'Weiter', 0, 0),
    (0, 'Hier klicken', 0, 0),
    (0, 'Hier', 0, 0),
    (0, 'Click here', 0, 0),
    (0, 'here', 0, 0),
    (0, 'Details', 0, 0),
    (0, 'Info', 0, 0),
    (0, 'Informationen', 0, 0),
    (0, 'Mehr Infos', 0, 0),
    (0, 'Mehr', 0, 0),
    (0, 'Weitere Informationen', 0, 0),
    (0, 'Weiterlesen', 0, 0),
    (0, 'Zum Artikel', 0, 0),
    (0, 'Zur Seite', 0, 0),
    (0, 'Mehr erfahren', 0, 0),
    (0, 'Learn more', 0, 0),
    (0, 'Discover', 0, 0),
    (0, 'Explore', 0, 0),
    (0, 'Link', 0, 0),
    (0, 'Mehr anzeigen', 0, 0),
    (0, 'Show more', 0, 0),
    (0, 'Weitere Details', 0, 0);